import { GraphQLObjectType, GraphQLInt, GraphQLString } from 'graphql';

export const ShiftType = new GraphQLObjectType({
  name: 'ShiftType',
  fields: () => ({
    ID: { type: GraphQLInt },
    AttendantID: { type: GraphQLString },
    Shift1: { type: GraphQLString },
    Shift2: { type: GraphQLString },
    Shift3: { type: GraphQLString },
    Shift4: { type: GraphQLString },
    Shift5: { type: GraphQLString },
    Shift6: { type: GraphQLString },
    Shift7: { type: GraphQLString },
    Shift8: { type: GraphQLString },
    Shift9: { type: GraphQLString },
    Shift10: { type: GraphQLString },
    Shift11: { type: GraphQLString },
    Shift12: { type: GraphQLString },
    Shift13: { type: GraphQLString },
    Shift14: { type: GraphQLString },
    Shift15: { type: GraphQLString },
    Shift16: { type: GraphQLString },
    Shift17: { type: GraphQLString },
    Shift18: { type: GraphQLString },
    Shift19: { type: GraphQLString },
    Shift20: { type: GraphQLString },
    Shift21: { type: GraphQLString },
    Shift22: { type: GraphQLString },
    Shift23: { type: GraphQLString },
    Shift24: { type: GraphQLString },
    Shift25: { type: GraphQLString },
    Shift26: { type: GraphQLString },
    Shift27: { type: GraphQLString },
    Shift28: { type: GraphQLString },
    Shift29: { type: GraphQLString },
    Shift30: { type: GraphQLString },
    Shift31: { type: GraphQLString },
  }),
});
